repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'source venv/bin/activate && cd backend && pytest'
        language: system
        types: [python]
        pass_filenames: false

      # - id: frontend-lint
      #   name: frontend-lint
      #   entry: bash -c 'cd frontend && npm run lint'
      #   language: system
      #   types: [javascript]
      #   pass_filenames: false

      # - id: frontend-test
      #   name: frontend-test
      #   entry: bash -c 'cd frontend && npm run test'
      #   language: system
      #   types: [javascript]
      #   pass_filenames: false
